### ISSUE TITLE
freezing on load

### ISSUE THREAD

**Issue by re2re2re2** [praydog/RE2-Mod-Framework#5]
Unable to load a saved game, freezes at loading screen.  Starting a new game results in progress bar reaching 10% and then freezing.

**Comment by praydog** [comment]
Try downloading the latest version. I've attempted a fix which I've addressed on #3

**Comment by re2re2re2** [comment]
Still freezing on the loading screen, no longer loads to 10%.

**Comment by re2re2re2** [comment]
The exe will not run at all with that one. With the others it would take or
three tries to get the game to start but this one never loads.

**Comment by praydog** [comment]
Alright, I think I've actually fixed it this time (the loading issue at least). Let me know if not.

**Comment by Hyperbog** [comment]
Hey praydog, 

Going to comment here as this also applies to the '4th Survivor' issue I posted. The new First Person build you uploaded addressed the loading issue. I was able to get-in game in the mode mentioned above without freezing at the 10% mark. Thanks again for the speedy response. Much appreciated.
